export default function () {
  return {
    onboarding: require('assets/images/temp.png'),
    TeraBankLogoIcon: require('assets/images/TeraBankLogoIcon.png'),
    BOGLogoIcon: require('assets/images/BOGLogoIcon.png'),
    TBCBankLogoIcon: require('assets/images/TBCBankLogoIcon.png'),
    VTBBankLogoIcon: require('assets/images/VTBBankLogoIcon.png'),
    BasisBankLogoIcon: require('assets/images/BasisBankLogoIcon.png'),
    CredoBankLogoIcon: require('assets/images/CredoBankLogoIcon.png'),
    IshBankLogoIcon: require('assets/images/IshBankLogoIcon.png'),
    KartuBankLogoIcon: require('assets/images/KartuBankLogoIcon.png'),
    KhalikBankLogoIcon: require('assets/images/KhalikBankLogoIcon.png'),
    LibertyBankLogoIcon: require('assets/images/LibertyBankLogoIcon.png'),
    PashaBankLogoIcon: require('assets/images/PashaBankLogoIcon.png'),
    PeiseraBankLogoIcon: require('assets/images/PeiseraBankLogoIcon.png'),
    ProcreditBankLogoIcon: require('assets/images/ProcreditBankLogoIcon.png'),
    SilkBankLogoIcon: require('assets/images/SilkBankLogoIcon.png'),
    ZiraatBankLogoIcon: require('assets/images/ZiraatBankLogoIcon.png'),
    PizzaIcon: require('assets/images/pizza.png'),
    AssetsIcon: require('assets/images/assets.png'),
    LiabilitiesIcon: require('assets/images/liabilities.png'),
    ChevronRight: require('assets/images/ChevronRight.png'),
    PensionIcon: require('assets/images/pensionImage.png'),
    OpenEye: require('assets/images/OpenEye.png'),
    CloseEye: require('assets/images/CloseEye.png'),
    Email: require('assets/images/Email.png'),
    Phone: require('assets/images/Phone.png'),
    Overdraft: require('assets/images/overdraft.png'),
    NotificationColored: require('assets/images/NotificationColored.png'),
    CurrencyRates: require('assets/images/CurrencyRates.png'),
    Locations: require('assets/images/Locations.png'),
    PensionFund: require('assets/images/PensionFund.png'),
    Finances: require('assets/images/Finances.png'),
    Documents: require('assets/images/Documents.png'),
    ThreeDotsIcon: require('assets/images/ThreeDots.png'),
  };
}
