import {
  DEPOSIT_SUCCESS_SCREEN,
  LOAN_REQUEST_ACCEPTED_SCREEN,
  TERA_WALLET_SUCCESS_SCREEN,
} from './ScreenNames';

export const tabHiddenRoutes = [
  DEPOSIT_SUCCESS_SCREEN,
  TERA_WALLET_SUCCESS_SCREEN,
  LOAN_REQUEST_ACCEPTED_SCREEN,
];
