export const URLS = {
  refreshToken: '/api/v1/Auth/RefreshToken',
  login: 'api/v1/Auth/Login',
  logout: '/api/v1/Auth/Logout',
  addTrustedDevice: '/api/v1/Auth/AddTrustedDevice',
  getTrustedDevices: '/api/v1/Auth/GetTrustedDevices',
  getTemplates: 'api/v1/Templates/GetTemplates',
  getUserProfile: 'api/v1/Customers/GetUserProfile',
  loginByRefreshToken: '/api/v1/Auth/LoginByRefreshToken',
  getCreditCard: 'api/v1/Loan/GetCreditCard',
  getOverdraft: 'api/v1/Loan/GetOverDraft',
  getLoanCustomerId: 'api/v1/Loan/GetLoanByCustomerId',
  getCustomperOps: 'api/v1/Transaction/GetCustomerOps',
  getAssets: 'api/v1/Deposit/GetDepositByClientId',
  getPensions: 'api/v1/Pensions/GetTotalSaving',
  getBankerInfo: 'api/v1/Customers/GetBankerInfo',
  getAccountsByCustomerId: 'api/v1/Account/GetAccountsByCustomerId',
  getOffers: 'api/v1/Offers/GetOffers',
  getCustomerOps: 'api/v1/Transaction/GetCustomerOps',
  getLoanSchedule: 'api/v1/Loan/GetLoanSchedule',
  getLoanHistory: 'api/v1/Loan/GetLoanPayments',
  BlockCard: 'api/v1/Account/BlockCard',
  UnblockCard: 'api/v1/Account/UnblockCard',
  getAmount: 'api/v1/transfers/ConvertAmount',
  transferToOwnAccount: 'api/v1/Transfers/TransferToOwnAccount',
  exchange: 'api/v1/Transfers/Exchange',
  getTransactionDetails: 'api/v1/Transaction/GetTransactionDetails',
};
